spring:
  application:
    name: rich-code-weaver-app
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rich_code_weaver
    username: root
    password: 12345
  # redis
  data:
    redis:
      database: 5
      port: 6379
      host: localhost
      password:
      user:
      # 连接超时时间
      timeout: 5000
      # 过期时间
      ttl: 5000
  profiles:
    active: local

server:
  port: 8101
  servlet:
    context-path: /
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# redisson 配置
redisson:
  connectionPoolSize: 10
  connectionMinimumIdleSize: 1
  idleConnectionTimeout: 30000
  connectTimeout: 5000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
#      paths-to-match: '/**'
      packages-to-scan: com.rich.app.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Spring Boot Admin Client 配置
spring.boot.admin.client:
  # Spring Boot Admin Server 地址
  url: http://localhost:9001
  instance:
    # 服务实例名称
    name: ${spring.application.name}
    # 服务访问地址
    service-base-url: http://localhost:${server.port}

# actuator 端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: '*'
  endpoint:
    health:
      # 显示详细健康信息
      show-details: always