spring:
  application:
    name: rich-code-weaver-user
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  profiles:
    active: local

server:
  port: 8102
  servlet:
    context-path: /
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
#      paths-to-match: '/**'
      packages-to-scan: com.rich.user.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Spring Boot Admin Client 配置
spring.boot.admin.client:
  # Spring Boot Admin Server 地址
  url: http://localhost:9001
  instance:
    # 服务实例名称
    name: ${spring.application.name}
    # 服务访问地址
    service-base-url: http://localhost:${server.port}

# actuator 端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: '*'
  endpoint:
    health:
      # 显示详细健康信息
      show-details: always