# 本地配置模板 ，使用需去除 "-tmp" 后缀

# 阿里云OSS配置
aliyun:
  oss:
    end-point:
    access-key-id:
    access-key-secret:
    bucket-name:

# Dubbo
dubbo:
  registry:
    # nacos 注册中心启动地址
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    # 协议端口
    port: 50053
  consumer:
    timeout: 150000
  provider:
    timeout: 150000